# One Docker registry that we will use for the challenge
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy ECR repositories for Timeoff Project - Released 2020-01-12'

Resources:
  Repository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: "applications/timeoff-management"

Outputs:

  EcrRepositoryId:
    Description: AWS Resource for ECR repository
    Value: !GetAtt Repository.Arn
    Export:
      Name: ecr-repository-timeoff-management
  TemplateVersion:
    Value: "0.1.0"

